jobs:
  grpcAspNetCoreServer:
    source:
      repository: https://github.com/JamesNK/grpc-dotnet
      branchOrCommit: jamesnk/benchmarch-grpcclient
      project: perf/benchmarkapps/GrpcAspNetCoreServer/GrpcAspNetCoreServer.csproj
    readyStateText: Application started
    waitForExit: false
    variables:
      enableCertAuth: false
      logLevel: None
    arguments: "--LogLevel {{logLevel}} --enableCertAuth {{enableCertAuth}}"